packaging_format = 2

id = "bookwyrm"
name = "BookWyrm"
description.en = "Platform for social reading"
description.fr = "Plateforme de lecture sociale"

version = "0.5.5~ynh1"

maintainers = ["oufmilo"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://joinbookwyrm.com/fr/"
demo = "https://joinbookwyrm.com/fr/"
admindoc = "https://docs.joinbookwyrm.com/"
code = "https://github.com/bookwyrm-social/bookwyrm"

[integration]
yunohost = ">= 11.1.14"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["de-de", "en-us", "es-es", "fr-fr", "it-it", "pt-pt", "zh-hans"]
    default = "fr-fr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
        url = "https://github.com/bookwyrm-social/bookwyrm/archive/refs/tags/v0.5.5.tar.gz"
        sha256 = "e09e7dff22e1d5aadb44c52d217fa53d3eaf2fece9aa9856a147987f0bbba14f"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000

    [resources.apt]
    packages = "postgresql postgresql-contrib python3-venv libpq-dev"

    [resources.database]
    type = "postgresql"
